---
title: "ds_proj"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r spe}

#DOWNLOADING

library(SpatialExperiment)
library(ggspavis)
library(scater)


(spe <- read10xVisium("/users/kshah/ovarian_cancer_forrest/outs/",
  type = "sparse",   # use sparse (not HDF5) format
  data = "filtered",      # read all (not filtered) data
  images = "lowres", # specify which image(s) to include
  load = TRUE))      # specify whether or not to load image(s)

assayNames(spe)

head(rowData(spe)) #only has symbol column (analogous to gene_name), does not have feature_type
head(colData(spe)) #does not have cell count column because cell segmentation was not done

head(spatialCoords(spe))

```

```{r qc}

#QUALITY CONTROL

plotSpots(spe)

is_mito <- grepl("(^MT-)|(^mt-)", rowData(spe)$symbol)
table(is_mito)
rowData(spe)$symbol[is_mito]
spe <- addPerCellQC(spe, subsets = list(mito = is_mito))
head(colData(spe))
hist(colData(spe)$subsets_mito_percent, breaks = 20)
qc_mito <- colData(spe)$subsets_mito_percent > 28 #none
table(qc_mito)

hist(colData(spe)$sum, breaks = 20)

qc_lib_size <- colData(spe)$sum < 600
table(qc_lib_size)
colData(spe)$qc_lib_size <- qc_lib_size
plotQC(spe, type = "spots", 
       discard = "qc_lib_size")

hist(colData(spe)$detected, breaks = 20)
qc_detected <- colData(spe)$detected < 400
table(qc_detected)
colData(spe)$qc_detected <- qc_detected
plotQC(spe, type = "spots", 
       discard = "qc_detected")

apply(cbind(qc_lib_size, qc_detected, qc_mito), 2, sum)

discard <- qc_lib_size | qc_detected | qc_mito
table(discard)

plotQC(spe, type = "spots", 
       discard = "discard")

#spe <- spe[, !colData(spe)$discard] this does not work for some reason, but the genes are the same for lib size and detected, so i just removed them

spe <- spe[, !colData(spe)$qc_lib_size]
dim(spe)

```

```{r norm}

#NORMALIZATION

library(scran)

# calculate library size factors
spe <- computeLibraryFactors(spe)
summary(sizeFactors(spe))
hist(sizeFactors(spe), breaks = 20)

# calculate logcounts and store in object
spe <- logNormCounts(spe)

# check
assayNames(spe)
dim(logcounts(spe))
```


```{r hvgs}

#FEATURE SELECTION

# fit mean-variance relationship
dec <- modelGeneVar(spe)

# remove 13 mitochondrial genes
spe <- spe[!is_mito, ]
dim(spe)

# visualize mean-variance relationship
fit <- metadata(dec)
plot(fit$mean, fit$var, 
     xlab = "mean of log-expression", ylab = "variance of log-expression")
curve(fit$trend(x), col = "dodgerblue", add = TRUE, lwd = 2)

# select top HVGs
top_hvgs <- getTopHVGs(dec, prop = 0.1)
length(top_hvgs) #1300 
```


```{r pca}

#DIMENSIONALITY REDUCTION

# compute PCA
set.seed(123)
top_hvgs_indices <- which(rownames(rowData(spe)) %in% top_hvgs)

spe <- runPCA(spe, subset_row = top_hvgs_indices)

reducedDimNames(spe)
dim(reducedDim(spe, "PCA"))

```

```{r clust}

#CLUSTERING

# graph-based clustering
set.seed(123)
k <- 10
g <- buildSNNGraph(spe, k = k, use.dimred = "PCA")
g_walk <- igraph::cluster_walktrap(g)
clus <- g_walk$membership
table(clus)

# store cluster labels in column 'label' in colData
colLabels(spe) <- factor(clus)

# plot clusters in spatial x-y coordinates
plotSpots(spe, annotate = "label", 
          palette = "libd_layer_colors")

# plot clusters in PCA reduced dimensions
plotDimRed(spe, type = "PCA", 
           annotate = "label", palette = "libd_layer_colors")

```


```{r clust2}

#CLUSTERING 2 bayesspace
#https://edward130603.github.io/BayesSpace/articles/BayesSpace.html

library(SingleCellExperiment)
library(ggplot2)
library(BayesSpace)

sce <- readVisium("/users/kshah/ovarian_cancer_forrest/outs")

set.seed(102)
sce <- spatialPreprocess(sce, platform="ST", 
                              n.PCs=50, n.HVGs=1300, log.normalize=TRUE)

sce <- qTune(sce, qs=seq(2, 10), platform="ST", d=7)
qPlot(sce)


# do clustering on JHPCE and save it in .rds file
#set.seed(149)
#sce <- spatialCluster(sce, q=4, platform="ST", d=7,
#                           init.method="mclust", model="t", gamma=2,
#                           nrep=10000, burn.in=1000,
#                           save.chain=TRUE)

sce <- readRDS(here("sce_ovarian_cancer_sample01_bayesspace.rds"))
clusterPlot(sce)

```


```{r clust3}

#CLUSTERING 3 precast
#https://feiyoung.github.io/PRECAST/articles/PRECAST.BreastCancer.html


# One sample
spe_to_seurat <- function(spe){
  
  # Get the log normalization
  
  # browser()
  # Find assay
  
  ret <- CreateSeuratObject(
    counts=assays(spe)$counts,
    meta.data=data.frame(
      row=spatialCoords(spe)[,1],
      col=spatialCoords(spe)[,2]),
      spot_id = colData(spe_sub)$spot_id
  )
  
  return(ret)
  
  
}


# Multiple sample
spe_to_seuratList <- function(spe){
  uniq_sample_id <- colData(spe)$sample_id |> unique()
  
  # Create a seurate object for each unique sample_id
  map(uniq_sample_id,
      .f = function(smp_id, spe){
        # browser()
        ret_spe <- spe[, colData(spe)$sample_id == smp_id]
        ret_seurat <- spe_to_seurat(ret_spe)
        
        return(ret_seurat)
      },
      spe = spe)
}


library(dplyr)
library(purrr)
library(Seurat)
library(SpatialExperiment)
library(PRECAST)

spe_sub <- read10xVisium("/users/kshah/ovarian_cancer_forrest/outs/",
  type = "sparse",   # use sparse (not HDF5) format
  data = "filtered",      # read all (not filtered) data
  images = "lowres", # specify which image(s) to include
  load = TRUE)     # specify whether or not to load image(s)

#use Boyi's code from https://github.com/boyiguo1/SRT_HPC_PRECAST/blob/master/R/example_script_of_PRECAST_pipeline.R
# SPE to SeuRat -----------------------------------------------------------
seuList <- spe_sub |> spe_to_seuratList()

# PRECAST -----------------------------------------------------------------

preobj <- CreatePRECASTObject(seuList = seuList)
preobj@seulist


PRECASTObj <- AddAdjList(preobj, platform = "Visium")
## Add a model setting in advance for a PRECASTObj object. verbose =TRUE helps outputing the
## information in the algorithm.
PRECASTObj <- AddParSetting(PRECASTObj, Sigma_equal = FALSE, coreNum = 1, maxIter = 30, verbose = TRUE)

PRECASTObj <- PRECAST(PRECASTObj, K = 15)
resList <- PRECASTObj@resList
PRECASTObj <- selectModel(PRECASTObj)

seuInt <- IntegrateSpaData(PRECASTObj, species = "Human")
seuInt

p_sp1 <- SpaPlot(seuInt, item = "cluster", point_size = 3, combine = F)[[1]] + cowplot::theme_cowplot() +
  ggplot2::ggtitle(paste0("PRECAST")) + ggplot2::xlab("row") + ggplot2::ylab("col")
seuInt <- AddTSNE(seuInt, n_comp = 2)
p_tsne <- dimPlot(seuInt, item = "cluster")
p_tsne <- p_tsne + cowplot::theme_cowplot() + ggplot2::ggtitle("PRECAST")

```



```{r clust4}

#CLUSTERING 4 deepST formatting

library(DropletUtils)
library(Matrix)
 
#https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/matrices
# set the different file paths of the filtered matrix
matrix_dir = "/users/kshah/ovarian_cancer_forrest/outs/filtered_feature_bc_matrix/"
barcode.path <- paste0(matrix_dir, "barcodes.tsv.gz")
features.path <- paste0(matrix_dir, "features.tsv.gz")
matrix.path <- paste0(matrix_dir, "matrix.mtx.gz")
 
# load the matrix.mtx.gz
mat_filtered <- readMM(file = matrix.path)
 
# load the feature.tsv.gz
feature.names = read.delim(features.path,
                           header = FALSE,
                           stringsAsFactors = FALSE)
 
# load the barcodes.tsv.gz
barcode.names = read.delim(barcode.path,
                           header = FALSE,
                           stringsAsFactors = FALSE)
 
# set the matrix column and row names                         
colnames(mat_filtered) = barcode.names$V1
rownames(mat_filtered) = feature.names$V1


write10xCounts(path = "/users/kshah/ovarian_cancer_forrest/outs/filtered_feature_bc_matrix.h5",
               x = mat_filtered,
               type = "HDF5",
               gene.id = unlist(feature.names[1]),
               gene.symbol = unlist(feature.names[2]),
               barcodes = unlist(barcode.names),
               library.ids = rep("random_input", 33538),
               overwrite = TRUE)

```



